packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.51.9
  '@trpc/client': ^11.0.0-rc.466
  '@trpc/react-query': ^11.0.0-rc.466
  '@trpc/server': ^11.0.0-rc.466
  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  zod: ^3.23.8
  date-fns: ^3.6.0
  date-fns-tz: ^3.1.3
  ky: ^1.7.0
  d3-scale: ^4.0.2
  '@types/d3-scale': ^4.0.8
  d3-interpolate: ^3.0.1
  '@types/d3-interpolate': ^3.0.4
  '@lunapaint/png-codec': ^0.2.0

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.3
    '@types/react-dom': ^18.3.0
